-- DROP TABLE IF EXISTS `student`;
-- CREATE TABLE `student` (
--   `id` bigint(20) NOT NULL,
--   `name` varchar(32) DEFAULT NULL,
--   `update_time` datetime DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- );
