# 数据源
spring:
  datasource:
    # mysql链接驱动，可不配置。默认从引入的pom中找
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # 批量更新sql需要设置&allowMultiQueries=true
    url: jdbc:mysql://39.106.164.245:3306/video?characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    # 连接池，可不配置。2.x默认使用该连接池
    type: com.zaxxer.hikari.HikariDataSource


# 日志输出，不配置不会输出sql日志
logging:
  level:
    com.duan.video: debug
